#!/usr/bin/python

import os
from flask import Flask, render_template, request
from flask_pymongo import PyMongo
from bson.objectid import ObjectId
from pymongo import MongoClient


app = Flask(__name__)
debug = 'DEVELOPMENT' in os.environ
app.config["MONGO_DBNAME"] = "GoldenShoe"
# set in vars in Heroku when deployed
MONGO_URI = os.environ.get("MONGO_URI")
app.config["MONGO_URI"] = MONGO_URI
db = MongoClient(MONGO_URI)
mongo = PyMongo(app)
app.config.update(SECRET_KEY=os.urandom(24))


# app.route decorator indicates which url calls the function
@app.route("/")
def home():
    carousel = db.GoldenShoe.products.find()
    # [-5:] here would cycle through the latest 5 items in the array
    items = list(carousel)[-5:]
    return render_template('home.html', items=items)


@app.route("/products", methods=["GET"])
# department and sale come from links from homepage to filter accordingly
def view_products(department=None, sale=False):
    query_object = {}
    if request.args.get("department"):
        # filter men's, women's or kid's from cards on home page
        query_object["department"] = request.args.get("department")
    elif request.args.get("sale"):
        # only show sale products from banner on home page
        query_object["sale"] = sale
    products = db.GoldenShoe.products.find(query_object)
    return render_template('products.html', products=products)


# <product_id> here make url responsive to the item clicked on 
@app.route("/product_detail/<product_id>/")
def product_detail(product_id):
    # ObjectId is generated by MongoDB
    product = db.GoldenShoe.products.find_one({"_id": ObjectId(product_id)})
    return render_template("product_detail.html", product=product)


# sets debug to true and runs locally is app.py is run
if __name__ == "__main__":
    app.run(host=os.environ.get("IP"), port=int(os.environ.get("PORT")),
            debug=True)
